import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import NavBar from "./components/Navbar";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

// Define the local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        >
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          {/* -------------Background Image Wrapper------------ */}
          <div className="relative min-h-screen">
            {/*-------------- Background Image --------------*/}
            <div className="absolute inset-0 bg-[url('/background.png')] bg-cover bg-center"></div>

            {/* -------------Content Wrapper ------------*/}
            <div className="relative z-10">
              <NavBar />
              {/*-------------- Main content ------------*/}
              <main>{children}</main>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
